pipeline {
    agent any
    
stage('ratings') {
            steps {
                script {
                    withCredentials([string(credentialsId: 'DockerHubCredentials', variable: 'DockerHubCredentials')]) {
                          sh 'docker login -u charlesjatto -p ${DockerHubCredentials}'
                          sh 'docker build -t charlesjatto/ratings:latest .'
                          sh 'docker push charlesjatto/ratings:latest'
                          sh 'docker rmi charlesjatto/ratings:latest'
                }
            }
        }
    }
}
