pipeline {
    agent any
    
   stage('mysql') {
            steps {
                script {
                    withCredentials([string(credentialsId: 'DockerHubCredentials', variable: 'DockerHubCredentials')]) {
                          sh 'docker login -u charlesjatto -p ${DockerHubCredentials}'
                          sh 'docker build -t charlesjatto/mysql:latest .'
                          sh 'docker push charlesjatto/mysql:latest'
                          sh 'docker rmi charlesjatto/mysql:latest'
                }
            }
        }
    }
}
