pipeline {
    agent any
    
    stage('catalogue') {
            steps {
                script {
                    withCredentials([string(credentialsId: 'DockerHubCredentials', variable: 'DockerHubCredentials')]) {
                          sh 'docker login -u charlesjatto -p ${DockerHubCredentials}'
                          sh 'docker build -t charlesjatto/catalogue:latest .'
                          sh 'docker push charlesjatto/catalogue:latest'
                          sh 'docker rmi charlesjatto/catalogue:latest'
                }
            }
        }
    }
}
